name: Generate design tokens

on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create input JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.client_payload.filename }}
          json: ${{ github.event.client_payload.tokens }}
          dir: 'input'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Verificar versão do Node.js
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Update dependencies (optional)
        run: npm update

      - name: Build
        run: npm run build --verbose

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'style: Update design tokens'
          title: ${{ github.event.client_payload.commitMessage || 'Update design tokens' }}
          body: 'Design tokens have been updated via Figma and need to be reviewed.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ou use PERSONAL_ACCESS_TOKEN se necessári
          BRANCH: 'create-pull-request/patch'
          continue-on-error: true  # Adiciona tolerância a erro